### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by Messilimeng** [leoliew/easemob-sdk#25]
[2017-03-21 17:28:05] [Error] TypeError: callback is not a function
    at Request._callback (E:\xiaoya\node_modules\easemob-sdk\lib\user.js:121:12)
    at Request.self.callback (E:\xiaoya\node_modules\easemob-sdk\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (E:\xiaoya\node_modules\easemob-sdk\node_modules\request\request.js:1082:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (E:\xiaoya\node_modules\easemob-sdk\node_modules\request\request.js:1009:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickDomainCallback (node.js:410:17)

**Comment by Messilimeng** [comment]
加个 qq 536403003

**Comment by leoliew** [comment]
在用这个方法的时候，请保证最后一个参数为 callback 所要处理的方法，例如: 
```
      easemobSDK.user.reset_password(username, newpassword, token, function (err, res, body) {
        should.not.exists(err);
        res.statusCode.should.equal(200);
        body.action.should.equal('set user password');
        done();
      });
```

**Comment by Messilimeng** [comment]
@leoliew 我发现这个没有缓存 accesstoken

**Comment by Messilimeng** [comment]
@leoliew 而且你的demo 上没有加 token 这个参数

**Comment by leoliew** [comment]
1 缓存要链接到自己的缓存服务器去实现，缓存那一块属于自己的业务,sdk 不包括的。
2 第三个参数不是token 么?

**Comment by Messilimeng** [comment]
@leoliew 没仔细看里面的代码 但是你的首页demo 是没有的 token的

**Comment by leoliew** [comment]
嗯，里面有unit test 的，如果要看看test 就行了 
readme 那里写错了, 刚改回来了， 😓

**Comment by leoliew** [comment]
多说一句，如果业务量不大，自建im 更好

**Comment by Messilimeng** [comment]
@leoliew 最好是吧accesstoken 放在 txt里面
